# [What is an exception](https://hyperskill.org/learn/step/7243)
다른 많은 언어와 마찬가지로 Kotlin에서는 예기치 않은 상황이 발생할 수 있습니다. 주로 프로그램을 작성한 후 실행하려고 할 때 이런 예외상황이 발생합시다. Kotlin 컴파일러는 코드가 올바르지 않다고 알려주면서 코드에 오류표시를 해줍니다. 그러나  Kotlin 컴파일러 모든 오류를 알려줄 수는00 없습니다. 따라서 구문상 정확하고 문제없이 컴파일 된 경우에도 프로그램이 실행되는 동안 오류가 발생할 수 있습니다. 이러한 상황을 코틀린에서는 `예외`라고합니다.

## Causing an exception
우선 예외를 설명하겠습니다. 분명히, 그것은 예기치 않은 일반적이지 않은 이벤트이며, 각기 다른 상황에서 발생해 여러 프로그래머를 성가시게 할수 있습니다. 다음 예제를 보면,
```kotlin
fun readNextInt(): Int {
    return readLine()!!.toInt()
}
 
fun runIncrementer() {
    val increment = 1 + readNextInt()
    println(increment)
}
 
fun main() {
    runIncrementer()
}
```
표준 입력에서 읽는 데 사용할 수있는 기능을 만들었습니다. 아주 간단한 예입니다. 한 줄을 읽고 그것을 숫자로 변환하고 결과값을 반환합니다. 이 코드에 문제가 있을까요?  
하지만, 사용자가 다음처럼 입력할 수도 있습니다.

```kotlin
> Hi :)
```
프로그램을 실행하고 이 줄을 입력하면 예외가 발생하고 프로그램은 다음과 같이 출력합니다.
```kotlin
Exception in thread "main" java.lang.NumberFormatException: For input string: "> Hi :)"
    at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
    at java.lang.Integer.parseInt(Integer.java:580)
    at java.lang.Integer.parseInt(Integer.java:615)
    at TmpKt.readNextInt(tmp.kt:2)
    at TmpKt.runIncrementer(tmp.kt:6)
    at TmpKt.main(tmp.kt:11)
    at TmpKt.main(tmp.kt)
```

## Reading an exception text
이 텍스트는 사용자에게 오류를 알리는 방법입니다. 사용자가 이 텍스트를 응용 프로그램 프로그래머에게 전달하면, 프로그래머는 이 오류를 해결하는 방법에 대해 좀더 쉽게 이해할 수 있습니다. 따라서 텍스트가 무엇을 의미하고 이것을 어떻게 읽어야 하는지 알아야 합니다.   
함께 읽어보겠습니다. 

우선, 예외 텍스트에는 `java`가 포함됩니다. 그 이유는 Kotlin/JVM으로 프로그램을 실행했기 때문입니다. Kotlin/Native와 같은 다른 환경에서는 다른텍스트가 표기됩니다.

`Exception in thread "main"`로 시작하는 줄은 예외가 발생했음을 알리고 스레드 이름을 알려줍니다. 지금은 스레드가 무엇인지 몰라도 괜찮습니다.

`java.lang.NumberFormatException: For input string: "> Hi :)` 이 텍스트는 예외 이름 (java.lang.NumberFormatException)과 메시지(For input string: "> Hi :)")를 보여줍니다.

> 이름은 예외의 종류를 나타냅니다. 그리고 메시지는 그것에 대해 구체적으로 설명해 줍니다. 


마지막으로 "at"로 시작하는 줄이 있습니다.

```kotlin
 at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
    at java.lang.Integer.parseInt(Integer.java:580)
    at java.lang.Integer.parseInt(Integer.java:615)
    at TmpKt.readNextInt(tmp.kt:2)
    at TmpKt.runIncrementer(tmp.kt:6)
    at TmpKt.main(tmp.kt:11)
    at TmpKt.main(tmp.kt)
```

이를 `stack trace`이라고 하며 예외가 발생한 위치를 보여줍니다. 함수 호출 위치를 추적 할 수 있습니다. 각 줄을 스택 추적 요소(stack trace element)라고 합니다. 보시다시피, 행에는 함수 이름 (forInputString, readNextInt, main), 파일 이름 (NumberFormatException.java, Integer.java, tmp.kt) 및 파일의 행 번호 (65, 615, 2, 6)가 포함됩니다.

또한 스택 추적 요소에는 클래스의 **canonical name**(java.lang.NumberFormatException, java.lang.Integer, TmpKt)이라고 하는 것이 포함됩니다. 이 이름을 사용하면 예외가 발생한 장소도 찾을 수 있습니다. 파일의 줄 번호 보다는 정확하지 않지만.. 사람이 읽고 이해할 수 있습니다.

> 지금은 class와 그들의 canonical name(정식 이름)을 다루지는 않고 다음에 알아보도록 하겠습니다. 이제 파일과 줄 번호를 사용하여 위치를 알 수 있습니다.

## Ordering of stack trace elements
stack trace 요소들의 순서는 매우 중요합니다. 추적은 이벤트에 가장 가까운 장소에서 시작하여 함수 호출의 첫 번째 장소로 내려갑니다.

예를 들어, trace를 보면 runIncrementer 함수가 tmp.kt 파일의 여섯 번째 행에서 readNextInt 함수를 호출하고 두 번째 행에서 parseInt 함수를 호출한다고 말할 수 있습니다. 마지막으로 스택 추적의 첫 번째 줄은 이벤트가 발생한 위치를 명확하게 나타냅니다.

하지만, 첫 번째 줄은 알지 못하는 내부 함수일 수 있기 때문에 문제를 이해하기 충분하기 않을 수도 있습니다.

이 예에서 네 번째 stack trace 요소는 함수에서 문제가 있는 위치를 보여줍니다. 그리고 세 번째 줄은 수정할 수 없는 내부 함수가 호출되었음을 보여줍니다. 어느 장소를 고쳐야 할까요? 첫벗째 스택 추적요소나 마지막 스택 추적 요소로 바로 확답할 수 없습니다. 상황에 따라 다를수 있기 때문입니다. 나중에 코드를 수정하는 방법에 대해 설명하지만 지금 이 상황에서는 tmp.kt : 6 행을 수정하는 것이 좋습니다. 
